import json
import tempfile
import unittest
from pathlib import Path
from unittest.mock import Mock, patch

import pandas as pd
import requests
from fastapi import HTTPException
from fastapi.testclient import TestClient

from src import analysis_pipeline, api, classifier, google_takeout, imports, music_pipeline, youtube_api

# ============================================================
# Behaviour Reference Fixtures
# ============================================================

REFERENCE_PATH = Path(__file__).parent / "fixtures" / "analysis_reference.json"
VIDEO_ID = "abcdefghijk"


def create_reference_dataframe():
    rows = []
    for index in range(40):
        rows.append({
            "title": ["Song A", "Song B", "Song C", "Song A", "Prison Labor - Persona 5 Royal OST [Extended]"][index % 5],
            "channel": "Artist " + str(index % 3),
            "channel_id": str(index % 3),
            "video_ids": str(index % 5),
            "video_duration": ["PT2M", "PT1H2M3S", "PT30S"][index % 3],
            "watched_at": pd.Timestamp("2026-01-01") + pd.Timedelta(days=index // 4 * 3, minutes=index % 4 * 20),
        })
    return pd.DataFrame(rows)


class BehaviourReferenceTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        # Captured before refactoring; these fixtures protect calculations and JSON contracts.
        cls.reference = json.loads(REFERENCE_PATH.read_text(encoding="utf-8"))

    def test_root_and_dashboard_routes(self):
        with TestClient(api.app) as client:
            self.assertEqual(client.get("/").json(), {"message": "YouTube Music Analysis API"})
            self.assertEqual(client.get("/dashboard/").status_code, 200)
            self.assertEqual(client.get("/dashboard/script.js").status_code, 200)

    def test_all_analysis_responses_match_original(self):
        dataframe = analysis_pipeline.prepare_analysis_dataframe(create_reference_dataframe())
        with patch.dict(api.app.dependency_overrides, {api.load_music_data: lambda: dataframe}):
            with TestClient(api.app) as client:
                for path, expected in self.reference.items():
                    if not path.startswith("/api/"):
                        continue
                    with self.subTest(path=path):
                        response = client.get(path, params={"title": "Song A"})
                        self.assertEqual(response.status_code, 200)
                        self.assertEqual(response.json(), expected)

    def test_classification_precedence_matches_original(self):
        decisions = [
            classifier.classify_music_candidate({
                "video_title": title, "channel_id": channel, "description": description,
            }, {"music"})
            for title in ["official audio", "reaction", "reaction music video", "song", "song top 10", "ordinary", "discovered", "COVER"]
            for channel in ["music", "other"]
            for description in ["", "Provided to YouTube by Label Released on: 2020 Auto-generated by YouTube"]
        ]
        self.assertEqual(decisions, self.reference["classification"])

    def test_personal_overrides_stay_disabled_for_imports(self):
        source = create_reference_dataframe()
        prepared = analysis_pipeline.prepare_analysis_dataframe(source, use_personal_overrides=False)
        self.assertTrue(prepared["duration_seconds"].equals(prepared["adjusted_duration_seconds"]))
        self.assertNotIn("duration_seconds", source.columns)

    def test_short_duration_boundary_and_explicit_labels(self):
        for duration, title, source_shorts, expected_calls, expected in [
            ("PT3M", "Song", set(), 1, None),
            ("PT3M1S", "Song", set(), 0, False),
            ("PT4M", "Song #short", set(), 0, True),
            ("PT4M", "Song", {VIDEO_ID}, 0, True),
            ("invalid", "Song", set(), 1, None),
        ]:
            with self.subTest(duration=duration, title=title, source_shorts=source_shorts):
                candidate = {"video_title": title, "video_duration": duration, "video_ID": VIDEO_ID}
                with patch.object(youtube_api, "is_short", return_value=None) as checker:
                    self.assertIs(music_pipeline.get_short_status(candidate, source_shorts), expected)
                    self.assertEqual(checker.call_count, expected_calls)

    def test_batches_preserve_order_at_api_limit(self):
        identifiers = [str(index) for index in range(101)]
        expected = [",".join(identifiers[:50]), ",".join(identifiers[50:100]), "100"]
        self.assertEqual(youtube_api.create_channel_batches(identifiers), expected)
        self.assertEqual(youtube_api.create_video_batches(pd.DataFrame({"video_ids": identifiers})), expected)

# ============================================================
# Malformed Data and Storage Failures
# ============================================================


class ErrorHandlingTests(unittest.TestCase):
    def test_malformed_metadata_is_reported(self):
        for metadata in [None, [], {}, {"items": None}]:
            with self.subTest(metadata=metadata):
                response = Mock()
                response.json.return_value = metadata
                with patch.object(youtube_api, "API_KEY", "test"), patch.object(youtube_api.requests, "get", return_value=response):
                    with self.assertRaisesRegex(ValueError, "malformed metadata"):
                        youtube_api.fetch_video_metadata(VIDEO_ID)

    def test_invalid_json_metadata_is_reported(self):
        response = Mock()
        response.json.side_effect = ValueError("invalid JSON")
        with patch.object(youtube_api, "API_KEY", "test"), patch.object(youtube_api.requests, "get", return_value=response):
            with self.assertRaisesRegex(ValueError, "invalid JSON metadata"):
                youtube_api.fetch_channel_metadata("channel")

    def test_http_failures_are_not_replaced_with_empty_metadata(self):
        response = Mock()
        response.raise_for_status.side_effect = requests.HTTPError("quota")
        with patch.object(youtube_api, "API_KEY", "test"), patch.object(youtube_api.requests, "get", return_value=response):
            with self.assertRaises(requests.HTTPError):
                youtube_api.fetch_video_metadata(VIDEO_ID)

    def test_malformed_optional_channel_and_url(self):
        self.assertIsNone(google_takeout.video_id_from_url("https://[invalid"))
        content = json.dumps([{
            "titleUrl": "https://youtu.be/" + VIDEO_ID,
            "title": "Watched Song", "time": "2026-01-01T00:00:00Z",
            "subtitles": {"unexpected": "object"},
        }])
        records = google_takeout.parse_watch_history_content(content, ".json")
        self.assertEqual(len(records), 1)
        self.assertIsNone(records[0]["channel"])

    def test_ambiguous_and_nonexistent_local_times_are_skipped(self):
        for timestamp in ["25 Oct 2026, 01:30:00", "29 Mar 2026, 01:30:00", "bad date"]:
            with self.subTest(timestamp=timestamp):
                self.assertTrue(pd.isna(google_takeout.parse_watch_timestamp(timestamp, "Europe/Dublin")))

    def test_corrupt_saved_status_is_reported(self):
        token = "a" * 43
        with tempfile.TemporaryDirectory() as folder, patch.object(imports, "IMPORT_ROOT", Path(folder)), patch.object(imports, "jobs", {}):
            status_path = Path(folder) / token / "status.json"
            status_path.parent.mkdir()
            for content in ["not json", "[]", '{"status": []}']:
                status_path.write_text(content, encoding="utf-8")
                with self.assertLogs(imports.logger, level="ERROR"), self.assertRaises(HTTPException) as error:
                    imports.get_job(token)
                self.assertEqual(error.exception.status_code, 500)

    def test_status_write_failure_releases_slot_and_reports_failure(self):
        token = "a" * 43
        with patch.object(imports, "jobs", {token: {"status": "processing", "message": "Queued"}}), patch.object(imports, "active", 1):
            with patch.object(imports, "write_import_status", side_effect=OSError("disk full")), self.assertLogs(imports.logger, level="ERROR"):
                imports.finish_import(token, {"status": "complete", "message": "Import complete"})
            self.assertEqual(imports.active, 0)
            self.assertEqual(imports.jobs[token]["status"], "failed")

    def test_initial_status_failure_releases_upload_slot(self):
        with patch.object(imports, "jobs", {}), patch.object(imports, "active", 0):
            with patch.object(imports, "write_import_status", side_effect=OSError("disk full")), self.assertLogs(imports.logger, level="ERROR"):
                response = TestClient(api.app).post("/api/imports", content=b"[]")
            self.assertEqual(response.status_code, 500)
            self.assertEqual(imports.active, 0)
            self.assertEqual(imports.jobs, {})

    def test_failed_replacement_preserves_saved_status(self):
        token = "a" * 43
        with tempfile.TemporaryDirectory() as folder, patch.object(imports, "IMPORT_ROOT", Path(folder)):
            initial_status = {"status": "processing", "message": "Queued"}
            imports.write_import_status(token, initial_status)
            with patch.object(Path, "replace", side_effect=OSError("disk full")):
                with self.assertRaises(OSError):
                    imports.write_import_status(token, {"status": "complete"})
            status_path = Path(folder) / token / "status.json"
            self.assertEqual(json.loads(status_path.read_text()), initial_status)
            self.assertFalse(status_path.with_suffix(".tmp").exists())

    def test_missing_report_has_explicit_error(self):
        with patch.object(api.pd, "read_csv", side_effect=FileNotFoundError), self.assertLogs(api.logger, level="ERROR"):
            response = TestClient(api.app).get("/api/summary")
        self.assertEqual(response.status_code, 500)
        self.assertEqual(set(response.json()), {"detail"})


if __name__ == "__main__":
    unittest.main()
