import re

# ============================================================
# Constants / Classification Rules
# ============================================================

STRONG_MUSIC_KEYWORDS = [
    "official audio",
    "music video",
    "lyric video",
    "lyrics",
    "remix",
    "instrumental",
    "full song",
    "歌ってみた",
]

STRONG_MUSIC_TOKENS = ["mv", "cover", "remix", "instrumental", "lyrics"]

WEAK_MUSIC_TOKENS = [ "song", "ost", "extended", "soundtrack"]

STRONG_NON_MUSIC_KEYWORDS = [
    "sound effect",
    "asmr",
    "reaction",
    "movie clip",
    "tv clip",
    "scene",
    "funny moments",]

STRONG_NON_MUSIC_TOKENS = [ "sfx" ]

WEAK_NON_MUSIC_KEYWORDS = [
    "ranking",
    "ranked",
    "top 10",
    "top 100",
    "listening to"
]

RELEASE_METADATA_PHRASES = [
    "provided to youtube by",
    "released on:",
    "auto-generated by youtube"
]

# ============================================================
# Initial Music Candidate Filtering (Removing non music videos and shorts)
# ============================================================

# YouTube category 10 is used as the initial music candidate filter.
# Further heuristics remove false positives and classify ambiguous candidates.
def extract_music_candidates(video_metadata):
    music_candidates = []

    for item in video_metadata["items"]:
        snippet = item["snippet"]
        content = item["contentDetails"]

        video_id = item["id"]
        video_title = snippet["title"]
        video_category = snippet["categoryId"]
        channel_name = snippet["channelTitle"]
        channel_id = snippet["channelId"]
        description = snippet["description"]
        video_duration = content["duration"]

        if video_category == "10":
            music_candidate_entry = {
                "video_title": video_title,
                "video_ID": video_id,
                "channel_name": channel_name,
                "channel_id": channel_id,
                "description": description,
                "video_duration": video_duration,
            }
            music_candidates.append(music_candidate_entry)

    return music_candidates

# Shorts frequently receive music metadata because of their backing audio,
# so they are removed before applying the remaining music heuristics.
def remove_shorts_video_candidates(
    music_candidates,
    is_short_function
):
    true_music_candidates = []

    for index, music_candidate in enumerate(music_candidates):
        print(
            f"Checking Short {index + 1}/{len(music_candidates)}"
        )

        if is_short_function(
            music_candidate.get("video_ID")
        ) is False:
            true_music_candidates.append(music_candidate)

    return true_music_candidates
# ============================================================
# Channel Classification (Identifying videos from music-dominant channels)
# ============================================================

# YouTube's music topic ID provides strong evidence that a channel primarily
# publishes music, but does not necessarily mean it is an official artist channel.
def is_music_channel(topic_details):
    return topic_details and "/m/04rlf" in topic_details.get("topicIds", [])


def extract_music_channel_ids(channel_metadata):
    music_channel_ids = set()

    for item in channel_metadata["items"]:
        channel_id = item["id"]
        topic_details = item.get("topicDetails")

        if is_music_channel(topic_details):
            music_channel_ids.add(channel_id)

    return music_channel_ids

# ============================================================
# Title Classification Helpers (Search/Matching functions for Video Titles)
# ============================================================

# Finds phrases anywhere within a title, allowing partial-string matches.
def find_keyword_matches(title, keywords):
    keywords_found = []

    for keyword in keywords:
        if keyword in title.lower():
            keywords_found.append(keyword)

    return keywords_found

# Finds standalone title tokens using word boundaries to avoid partial matches.
def find_token_matches(title, keywords):
    tokens_found = []

    for keyword in keywords:
        pattern = rf"\b{re.escape(keyword)}\b"

        if re.search(pattern, title, re.IGNORECASE):
            tokens_found.append(keyword)

    return tokens_found

# Classifies title evidence independently of channel and description evidence.
# Strong evidence determines a classification; weak evidence is retained for
# the final candidate classifier.
def classify_title(title):
    classification = ""
    strong_music_matches = (find_keyword_matches(title, STRONG_MUSIC_KEYWORDS)
                             + find_token_matches(title, STRONG_MUSIC_TOKENS) )

    weak_music_matches = find_token_matches(title, WEAK_MUSIC_TOKENS)

    strong_non_music_matches = (find_keyword_matches(title, STRONG_NON_MUSIC_KEYWORDS)
                                + find_token_matches(title, STRONG_NON_MUSIC_TOKENS) )

    weak_non_music_matches = (find_keyword_matches(title, WEAK_NON_MUSIC_KEYWORDS))


    if strong_music_matches and not strong_non_music_matches:
        classification = "music"

    elif strong_non_music_matches and not strong_music_matches:
        classification = "non-music"

    elif strong_music_matches and strong_non_music_matches:
        classification = "conflict"

    else:
        classification = "uncertain"

    return {
        "classification": classification,
        "strong_music_matches": strong_music_matches,
        "weak_music_matches": weak_music_matches,
        "strong_non_music_matches": strong_non_music_matches,
        "weak_non_music_matches": weak_non_music_matches,
    }

# ============================================================
# Description Classification
# Automatically distributed YouTube music releases contain a consistent set
# of metadata phrases that can provide strong music evidence.
# ============================================================

def is_distributed_music_release(description):
    if not description:
        return False

    description = description.lower()

    return all(
        phrase in description
        for phrase in RELEASE_METADATA_PHRASES
    )

# ============================================================
# Final Candidate Classification
# (Integrate Channel, Title and Description classification and give reasoning for identification)
# ============================================================

def classify_music_candidate(candidate, music_channel_ids):
    def result(classification, reason, evidence=None):
        return {
            "video_title": title,
            "classification": classification,
            "reason": reason,
            "evidence": evidence
        }

    title = candidate["video_title"]
    channel_id = candidate["channel_id"]
    description = candidate["description"]

    title_result = classify_title(title)

    # Strong negative title evidence takes precedence over channel evidence.
    if title_result["classification"] == "non-music":
        return result(
            "non_music",
            "strong_non_music_title",
            title_result["strong_non_music_matches"]
        )

    # Channel has the YouTube music topic (not proof of official artist status).
    if channel_id in music_channel_ids:
        return result(
            "confirmed_music",
            "music_channel"
        )

    # strong positive evidence/keywords in the video title
    if title_result["classification"] == "music":
        return result("confirmed_music",
            "strong_music_title",
            title_result["strong_music_matches"]
            )

    # conflicting strong title evidence
    if title_result["classification"] == "conflict":
        return result(
            "review",
            "conflicting_strong_title_evidence",
            title_result
        )

    # distributed music release
    if is_distributed_music_release(description):
        return result(
            "confirmed_music",
            "distributed_music_release"
        )

    # Weak evidence/ie unofficial music release from unofficial channel
    weak_music = title_result["weak_music_matches"]
    weak_non_music = title_result["weak_non_music_matches"]

    if weak_music and not weak_non_music:
        return result(
            "probable_music",
            "weak_music_title",
            weak_music
        )

    if weak_music and weak_non_music:
        return result(
            "review",
            "conflicting_weak_title_evidence",
            title_result
        )

    # Category 10 is still evidence!
    return result(
        "probable_music",
        "youtube_music_category_only"
    )

def classify_candidates(candidates, music_channel_ids):
    classified_candidates = []
    for candidate in candidates:
        result = classify_music_candidate(candidate, music_channel_ids)
        classified_candidates.append({
            **candidate,
            "classification": result["classification"],
            "classification_reason": result["reason"],
            "classification_evidence": result["evidence"],
        })
    return classified_candidates
